# Generated by Django 5.1.4 on 2025-01-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintegration',
            name='site_id',
            field=models.CharField(blank=True, help_text='Site Id fournie par le fournisseur de paiement.', max_length=255, null=True, verbose_name='Id du Site'),
        ),
    ]
