# Generated by Django 5.1.4 on 2025-01-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fournisseur'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.expense'),
        ),
        migrations.AddField(
            model_name='feeding',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.batch'),
        ),
        migrations.AddField(
            model_name='feeding',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.feed'),
        ),
        migrations.AddField(
            model_name='provision',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.feed'),
        ),
        migrations.AddField(
            model_name='provision',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fournisseur'),
        ),
        migrations.AddField(
            model_name='stockloss',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_losses', to='management.feed'),
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.batch'),
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.treatment'),
        ),
    ]
